### ISSUE TITLE
train vecorize model

### ISSUE THREAD

**Issue by dajinstory** [dajinstory/AI_Bartender#32]
정재가
feature/#32 branch에서
AI_Bartender\deep_learning\1_vectorize에서

tutorial의 코드를 wine 데이터에 맞춰서 코드를 수정하고
와인데이터에 맞게 학습을 마저 시킨다.

**Comment by JungJaeLee-JJ** [comment]
finished the task, and vectorized data is saved as .csv file in classify folder.
